# Generated by Django 3.1.3 on 2020-12-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201209_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='pincode',
            new_name='zipcode',
        ),
    ]
